projectmilestone:
  vtiger_projectmilestone:
    columns:
      projectmilestonename:
        formatter: words
      projectmilestonedate:
        provider: Faker\Provider\DateTime
        formatter: date
