cbsurveydone:
  vtiger_cbsurveydone:
    columns:
      surveydonedate:
        provider: Faker\Provider\DateTime
        formatter: dateTimeThisCentury
      cbsd_providerid:
        formatter: uuid
      cbsq_token:
        formatter: uuid
      cbsq_addinfo:
        provider: Faker\Provider\en_US\Text
        formatter: realText
      cbsq_hiddeninfo:
        provider: Faker\Provider\en_US\Text
        formatter: realText
