mailscanner:
  vtiger_mailscanner:
    provider:
      delete: true
  vtiger_mailscanner_actions:
    provider:
      delete: true
  vtiger_mailscanner_folders:
    provider:
      delete: true
  vtiger_mailscanner_ids:
    provider:
      delete: true
  vtiger_mailscanner_ruleactions:
    provider:
      delete: true
  vtiger_mailscanner_rules:
    provider:
      delete: true
