leadaddress:
  vtiger_leadaddress:
    columns:
      city:
        provider: Faker\Provider\en_US\Address
        formatter: city
      code:
        provider: Faker\Provider\en_US\Address
        formatter: postcode
      state:
        provider: Faker\Provider\en_US\Address
        formatter: state
      pobox:
        provider: Faker\Provider\en_US\Address
        formatter: buildingNumber
      country:
        provider: Faker\Provider\en_US\Address
        formatter: country
      phone:
        formatter: phoneNumber
      mobile:
        formatter: phoneNumber
      fax:
        formatter: faxNumber
      lane:
        provider: Faker\Provider\en_US\Address
        formatter: address
