products:
  vtiger_products:
    columns:
      productname:
        formatter: sentence
      website:
        provider: Faker\Provider\Internet
        formatter: url
      unit_price:
        formatter: randomFloat
      cost_price:
        formatter: randomFloat
      productcode:
        formatter: ean13
      vendor_part_no:
        formatter: ean8
      mfr_part_no:
        formatter: ean8
      productsheet:
        nullColumnBeforeRun: true
      serialno:
        formatter: ean13
      imagename:
        nullColumnBeforeRun: true
