cbsurvey:
  vtiger_cbsurvey:
    columns:
      cbsurveyname:
        formatter: sentence
      cbsurveyprovider:
        provider: Faker\Provider\en_US\Company
        formatter: company
      cbsurveyurl:
        formatter: url
      cbsurveystart:
        provider: Faker\Provider\DateTime
        formatter: dateTimeThisCentury
      cbsurveyend:
        provider: Faker\Provider\DateTime
        formatter: dateTimeThisCentury
