cbMap:
  vtiger_cbmap:
    provider:
      delete: true
      where: "maptype != 'Record Access Control' and
              maptype != 'Condition Expression' and
              maptype != 'Condition Query' and
              maptype != 'Mapping' and
              maptype != 'Record Set Mapping' and
              maptype != 'Module Set Mapping' and
              maptype != 'ListColumns' and
              maptype != 'DuplicateRelations' and
              maptype != 'MasterDetailLayout' and
              maptype != 'IOMap' and
              maptype != 'FieldDependency' and
              maptype != 'Validations' and
              maptype != 'Import' and
              maptype != 'RelatedPanes' and
              maptype != 'FieldInfo' and
              maptype != 'GlobalSearchAutocomplete' and
              maptype != 'Field Set Mapping' and
              maptype != 'Detail View Layout Mapping'"