project:
  vtiger_project:
    columns:
      projectname:
        formatter: domainWord
      project_no:
        formatter: project_no
      startdate:
        provider: Faker\Provider\DateTime
        formatter: date
      targetenddate:
        provider: Faker\Provider\Internet
        formatter: date
      targetbudget:
        formatter: targetbudget
      projecturl:
        provider: Faker\Provider\Internet
        formatter: url
      projectstatus:
        formatter: projectstatus
      projectpriority:
        formatter: projectpriority
      projecttype:
        formatter: projecttype
      progress:
        formatter: progress
      linktoaccountscontacts:
        formatter: linktoaccountscontacts
      email:
        provider: Faker\Provider\Internet
        formatter: email
