cbsurveyquestion:
  vtiger_cbsurveyquestion:
    columns:
      cbsq_providerid:
        formatter: uuid
      cbsquestion:
        provider: Faker\Provider\en_US\Text
        formatter: realText
      cbsanswer:
        provider: Faker\Provider\en_US\Text
        formatter: realText
