accountshipads:
  vtiger_accountshipads:
    columns:
      ship_city:
        provider: Faker\Provider\en_US\Address
        formatter: city
      ship_country:
        provider: Faker\Provider\en_US\Address
        formatter: country
      ship_state:
        provider: Faker\Provider\en_US\Address
        formatter: state
      ship_pobox:
        provider: Faker\Provider\en_US\Address
        formatter: buildingNumber
      ship_street:
        provider: Faker\Provider\en_US\Address
        formatter: streetName
      ship_code:
        provider: Faker\Provider\en_US\Address
        formatter: postcode

