projecttask:
  vtiger_projecttask:
    columns:
      projecttaskname:
        formatter: words
      startdate:
        formatter: date
      enddate:
        formatter: date
      projectid:
        formatter: projectid
      email:
        formatter: email
