smsnotifier_status:
  vtiger_smsnotifier_status:
    columns:
      smsnotifierid:
        formatter: smsnotifierid
      tonumber:
        provider: Faker\Provider\PhoneNumber
        formatter: phoneNumber
      status:
        formatter: status
      smsmessageid:
        formatter: smsmessageid
      statusmessage:
        formatter: statusmessage
