cobropago:
  vtiger_cobropago:
    columns:
      reference:
        formatter: words
      amount:
        formatter: randomFloat
      cost:
        formatter: randomFloat
      benefit:
        formatter: randomFloat
      update_log:
        nullColumnBeforeRun: true
