troubletickets:
  vtiger_troubletickets:
    columns:
      title:
        formatter: words
      update_log:
        nullColumnBeforeRun: true
      email:
        provider: Faker\Provider\Internet
        formatter: email
      solution:
        formatter: text
  vtiger_ticketcomments:
    columns:
      comments:
        formatter: text
