ticketcomments:  
  vtiger_ticketcomments:
    columns:
      ticketid:
        formatter: ticketid
      comments:
        formatter: comments
      ownerid:
        formatter: ownerid
      ownertype:
        formatter: ownertype
      createdtime:
        formatter: createdtime
