emaildetails:
  vtiger_emaildetails:
    columns:
      from_email:
        provider: Faker\Provider\Internet
        formatter: email
      to_email:
        provider: Faker\Provider\Internet
        formatter: email
      cc_email:
        provider: Faker\Provider\Internet
        formatter: email
        optional: true
      bcc_email:
        provider: Faker\Provider\Internet
        formatter: email
        optional: true
      replyto:
        formatter: email
        optional: true
