users:
  vtiger_users:
    provider:
      where: " user_name != 'admin' "
    columns:
      user_name:
        formatter: userName
      ename:
        formatter: userName
      user_password:
        formatter: shuffle
      first_name:
        formatter: firstName
      last_name:
        formatter: lastName
      description:
        formatter: test
      title:
        formatter: title
      phone_home:
        formatter: phoneNumber
      phone_mobile:
        formatter: phoneNumber
      phone_work:
        formatter: phoneNumber
      phone_other:
        formatter: phoneNumber
      phone_fax:
        formatter: faxNumber
      email1:
        provider: Faker\Provider\Internet
        formatter: email
      email2:
        provider: Faker\Provider\Internet
        formatter: email
        optional: true
      secondaryemail:
        provider: Faker\Provider\Internet
        formatter: email
        optional: true
      signature:
        formatter: word
      address_street:
        provider: Faker\Provider\Address
        formatter: streetName
      address_city:
        provider: Faker\Provider\en_US\Address
        formatter: city
      address_state:
        provider: Faker\Provider\en_US\Address
        formatter: state
      address_country:
        provider: Faker\Provider\en_US\Address
        formatter: country
      address_postalcode:
        provider: Faker\Provider\en_US\Address
        formatter: postcode
      imagename:
        nullColumnBeforeRun: true
      accesskey:
        formatter: password
