cbcompany:
  vtiger_cbcompany:
    columns:
      companyname:
        provider: Faker\Provider\en_US\Company
        formatter: company
      comercialname:
        provider: Faker\Provider\en_US\Company
        formatter: company
      siccode:
        formatter: swiftBicNumber
      phone:
        provider: Faker\Provider\en_HK\PhoneNumber
        formatter: phoneNumber
      fax:
        provider: Faker\Provider\en_HK\PhoneNumber
        formatter: faxNumber
      website:
        formatter: url
      address:
        provider: Faker\Provider\en_US\Address
        formatter: address
      city:
        provider: Faker\Provider\en_US\Address
        formatter: city
      state:
        provider: Faker\Provider\en_US\Address
        formatter: state
      postalcode:
        provider: Faker\Provider\en_US\Address
        formatter: postcode
      country:
        provider: Faker\Provider\en_US\Address
        formatter: country
      email:
        formatter: email
      companybr:
        formatter: text
      companylopd:
        formatter: text
      companylogo:
        nullColumnBeforeRun: true
      applogo:
        nullColumnBeforeRun: true
      favicon:
        nullColumnBeforeRun: true
