accounts:
  vtiger_account:
    columns:
      accountname:
        provider: Faker\Provider\en_US\Company
        formatter: company
      annualrevenue:
        formatter: randomFloat
        nbMaxDecimals: 2
        min: 100
        max: 100000
      ownership:
        formatter: word
      siccode:
        formatter: swiftBicNumber
      tickersymbol:
        formatter: word
      phone:
        formatter: phoneNumber
      otherPhone:
        formatter: phoneNumber
        optional: true
      email1:
        formatter: email
      email2:
        formatter: email
        optional: true
      website:
        formatter: url
      fax:
        provider: Faker\Provider\en_US\PhoneNumber
        formatter: faxNumber
