globalvariable:
  vtiger_globalvariable:
    provider:
      delete: true
      where: "gvname != 'Debug_Record_Not_Found' and 
              gvname != 'Debug_Report_Query' and
              gvname != 'Debug_ListView_Query' and
              gvname != 'Debug_RelatedList_Query' and
              gvname != 'Debug_Popup_Query' and
              gvname != 'Debug_Email_Sending' and
              gvname != 'Debug_Calculate_Response_Time' and
              gvname != 'Debug_ActivityReminder_Deactivated' and
              gvname != 'Debug_Access_Restricted_File' and
              gvname != 'Application_Global_Search_SelectedModules' and
              gvname != 'Application_Global_Search_Binary' and
              gvname != 'Application_Global_Search_TopModules' and
              gvname != 'Application_Global_Search_Active' and
              gvname != 'Application_Global_Search_Autocomplete_Limit' and
              gvname != 'Application_ProductService_Search_Autocomplete_Limit' and
              gvname != 'Application_Storage_Directory' and
              gvname != 'Application_Storage_SaveStrategy' and
              gvname != 'Application_OpenRecordInNewXOnRelatedList' and
              gvname != 'Application_OpenRecordInNewXOnListView' and
              gvname != 'Application_MaxFailedLoginAttempts' and
              gvname != 'Application_ExpirePasswordAfterDays' and
              gvname != 'Application_DetailView_Inline_Edit' and
              gvname != 'Application_DetailView_Record_Navigation' and
              gvname != 'Application_DetailView_Sticky_BlockStatus' and 
              gvname != 'Application_Filter_All_Edit' and
              gvname != 'Application_EditView_Submit_Form_WithEnter' and
              gvname != 'Application_TrackerMaxHistory' and
              gvname != 'Application_Display_World_Clock' and
              gvname != 'Application_Display_Mini_Calendar' and
              gvname != 'Application_Use_RTE' and
              gvname != 'Application_RTESpellcheck' and
              gvname != 'Application_Default_Action' and
              gvname != 'Application_Default_Module' and
              gvname != 'Application_Allow_Exports' and
              gvname != 'Application_ListView_MaxColumns' and
              gvname != 'Application_ListView_Max_Text_Length' and
              gvname != 'Application_ListView_PageSize' and
              gvname != 'Application_ListView_Default_Sort_Order' and
              gvname != 'Application_ListView_Default_OrderDirection' and
              gvname != 'Application_ListView_Record_Change_Indicator' and
              gvname != 'Application_ListView_Default_Sorting' and
              gvname != 'Application_ListView_Compute_Page_Count' and
              gvname != 'Application_ListView_Sum_Currency' and
              gvname != 'Application_ListView_SearchColumns' and
              gvname != 'Application_ListView_SearchColumns_AC_Trigger' and
              gvname != 'Application_SaveAndRepeatActive' and
              gvname != 'Application_Upload_MaxSize' and
              gvname != 'Application_Single_Pane_View' and
              gvname != 'Application_Minimum_Cron_Frequency' and
              gvname != 'Application_UI_ShowGITVersion' and
              gvname != 'Application_UI_ShowGITDate' and
              gvname != 'Application_UI_Version' and
              gvname != 'Application_Group_Selection_Permitted' and
              gvname != 'Application_B2B' and
              gvname != 'Application_Permit_Assign_Up' and
              gvname != 'Application_Permit_Assign_SameRole' and
              gvname != 'Application_Permit_Assign_AllGroups' and
              gvname != 'Application_User_SortBy' and
              gvname != 'Application_SendUserPasswordByEmail' and
              gvname != 'Application_Pagination_Limit' and
              gvname != 'Application_Popup_Address_Selection' and
              gvname != 'Application_PopupScreen_Width' and
              gvname != 'Application_PopupScreen_Height' and
              gvname != 'Application_Merge_Record_Limit' and
              gvname != 'Application_Textarea_Style' and
              gvname != 'Application_CSS_Properties' and
              gvname != 'Graph_DataLabels' and
              gvname != 'Graph_DataLabels_Color' and
              gvname != 'Graph_ColorScheme' and
              gvname != 'RelatedList_Activity_DefaultStatusFilter' and
              gvname != 'Calendar_Modules_Panel_Visible' and
              gvname != 'Calendar_Default_Reminder_Minutes' and
              gvname != 'Calendar_Slot_Minutes' and
              gvname != 'Calendar_Slot_Event_Overlap' and
              gvname != 'Calendar_Show_Inactive_Users' and
              gvname != 'Calendar_Show_Group_Events' and
              gvname != 'Calendar_Status_Panel_Visible' and
              gvname != 'Calendar_Push_End_On_Start_Change' and
              gvname != 'Calendar_PopupReminder_DaysPast' and
              gvname != 'Calendar_Priority_Panel_Visible' and
              gvname != 'Calendar_Show_Only_My_Events' and
              gvname != 'Calendar_Show_WeekNumber' and
              gvname != 'Calendar_goDirectToDetailView' and
              gvname != 'CronTasks_cronWatcher_TimeThreshold' and
              gvname != 'SMSNotifier_SendCopyToUser' and
              gvname != 'BusinessQuestion_TableAnswer_Limit' and
              gvname != 'BusinessMapping_SalesOrder2Invoice' and
              gvname != 'BusinessMapping_PotentialOnCampaignRelation' and
              gvname != 'BusinessMapping_Quotes2Invoice' and
              gvname != 'BusinessMapping_Quotes2SalesOrder' and
              gvname != 'Mobile_Module_by_default' and
              gvname != 'Mobile_Related_Modules' and
              gvname != 'Mobile_UI_Enabled' and
              gvname != 'Webservice_showUserAdvancedBlock' and
              gvname != 'Webservice_PermitQueryOnInactiveUsers' and
              gvname != 'Webservice_Enabled' and
              gvname != 'WebService_Session_Life_Span' and
              gvname != 'WebService_Session_Idle_Time' and
              gvname != 'Webservice_Describe_ReturnUserList' and
              gvname != 'Webservice_Describe_ReturnGroupList' and
              gvname != 'Webservice_Sync_RecordLimit' and
              gvname != 'Webservice_Sync_RecordLimitStreaming' and
              gvname != 'Webservice_GenDocConversion_Active' and
              gvname != 'SOAP_CustomerPortal_Enabled' and
              gvname != 'SOAP_Outlook_Enabled' and
              gvname != 'WEBDAV_Enabled' and
              gvname != 'Users_ReplyTo_SecondEmail' and
              gvname != 'Users_Default_Send_Email_Template' and
              gvname != 'Users_Select_Inactive' and
              gvname != 'User_AuthenticationType' and
              gvname != 'Accounts_BlockDuplicateName' and
              gvname != 'Campaign_CreatePotentialOnAccountRelation' and
              gvname != 'Campaign_CreatePotentialOnContactRelation' and
              gvname != 'GoogleCalendarSync_BaseUpdateMonths' and
              gvname != 'GoogleCalendarSync_BaseCreateMonths' and
              gvname != 'Import_Full_CSV' and
              gvname != 'Import_Batch_Limit' and
              gvname != 'Import_Scheduled_Limit' and
              gvname != 'Import_Launch_EventsAndWorkflows' and
              gvname != 'Import_LeaveUserReferenceFieldEmpty' and
              gvname != 'Import_DuplicateRecordHandling_Open' and
              gvname != 'Import_DuplicateRecordHandling_Type' and
              gvname != 'Export_Field_Separator_Symbol' and
              gvname != 'Export_RelatedField_GetValueFrom' and
              gvname != 'Export_RelatedField_NameForSearch' and
              gvname != 'Lead_Convert_TransferToAccount' and
              gvname != 'Lead_Convert_OpportunitySelected' and
              gvname != 'Lead_Convert_ContactSelected' and
              gvname != 'Product_Copy_Bundle_OnDuplicate' and
              gvname != 'Product_Show_Subproducts_Popup' and
              gvname != 'Product_Permit_Relate_Bundle_Parent' and
              gvname != 'Product_Permit_Subproduct_Be_Parent' and
              gvname != 'Product_Maximum_Number_Images' and
              gvname != 'Product_SubProduct_PriceRollUp' and
              gvname != 'Product_SubProduct_CostRollUp' and
              gvname != 'PurchaseOrder_TransferCostPrice' and
              gvname != 'PurchaseOrder_IgnoreTransferDiscount' and
              gvname != 'Workflow_Email_GenDoc_Attachment_Name' and
              gvname != 'Workflow_ListView_PageSize' and
              gvname != 'ModComments_DefaultCriteria' and
              gvname != 'ModComments_DefaultBlockStatus' and
              gvname != 'ModComments_Export_Format' and
              gvname != 'ModComments_Edit_Inline' and
              gvname != 'EMail_OpenTrackingEnabled' and
              gvname != 'Email_Attachments_Folder' and
              gvname != 'EMail_Maximum_Number_Attachments' and
              gvname != 'EMail_CustomCurrentDate_Format' and
              gvname != 'EMail_Less_Strict_ContentClean' and
              gvname != 'EMail_Send_Individual' and
              gvname != 'EMail_Signature_BeforeQuote' and
              gvname != 'MailManager_Show_SentTo_Links' and
              gvname != 'ToolTip_MaxFieldValueLength' and
              gvname != 'ToolTip_NumberOfComments' and
              gvname != 'HelpDesk_Sort_Comments_ASC' and
              gvname != 'Document_Folder_View' and
              gvname != 'Document_CreateSelectContactFolder' and
              gvname != 'Document_CreateSelectAccountFolder' and
              gvname != 'Document_CreateSelectAccountFolderForContact' and
              gvname != 'Attachment_ShowDownloadName' and
              gvname != 'HomePage_Widget_Group_Size' and
              gvname != 'GenDoc_CopyLabelToClipboard' and
              gvname != 'GenDoc_Convert_URL' and
              gvname != 'CobroPago_Invoice_Status_OnPaid' and
              gvname != 'CobroPago_PurchaseOrder_Status_OnPaid' and
              gvname != 'CobroPago_SalesOrder_Status_OnPaid' and
              gvname != 'Report_Send_Scheduled_ifEmpty' and
              gvname != 'Report_ListView_PageSize' and
              gvname != 'Report_MaxRows_OnScreen' and
              gvname != 'Report_MaxRelated_Modules' and
              gvname != 'Report_HeaderOnXLS' and
              gvname != 'Report_HeaderOnPDF' and
              gvname != 'Inventory_ListPrice_ReadOnly' and
              gvname != 'Inventory_Comment_Style' and
              gvname != 'Inventory_Show_ShippingHandlingCharges' and
              gvname != 'Inventory_Check_Invoiced_Lines' and
              gvname != 'Inventory_Tax_FillInMode' and
              gvname != 'Inventory_Quantity_Precision' and
              gvname != 'Inventory_Other_Modules' and
              gvname != 'Inventory_DoNotUseLines' and
              gvname != 'GContacts_Max_Results' and
              gvname != 'CustomerPortal_PDF_Modules' and
              gvname != 'CustomerPortal_PDF' and
              gvname != 'CustomerPortal_PDFTemplate_Quote' and
              gvname != 'CustomerPortal_PDFTemplate_SalesOrder' and
              gvname != 'CustomerPortal_PDFTemplate_Invoice' and
              gvname != 'CustomerPortal_PDFTemplate_PurchaseOrder' and
              gvname != 'CustomerPortal_Default_User' and
              gvname != 'Project_Gantt_Type' and
              gvname != 'RecordVersioningModules' and
              gvname != 'Security_ImageCheck' and
              gvname != 'MasterDetail_ReloadScreenAfterEdit'"