cbsurveyanswer:
  vtiger_cbsurveyanswer:
    columns:
      cbsa_providerid:
        provider: Faker\Provider\en_US\Text
        formatter: cbsa_providerid
      cbsurveyanswer:
        provider: Faker\Provider\en_US\Text
        formatter: realText
