service:
  vtiger_service:
    columns:
      servicename:
        formatter: sentence
      website:
        provider: Faker\Provider\Internet
        formatter: url
      unit_price:
        formatter: randomFloat
      cost_price:
        formatter: randomFloat
