campaign:
  vtiger_campaign:
    columns:
      campaignname:
        formatter: sentence
      expectedrevenue:
        formatter: randomFloat
      budgetcost:
        formatter: randomFloat
      actualcost:
        formatter: randomFloat
      sponsor:
        formatter: name
      targetaudience:
        formatter: sentence
      expectedsalescount:
        formatter: sentence
      actualsalescount:
        formatter: sentence
      expectedresponsecount:
        formatter: sentence
      actualresponsecount:
        formatter: sentence
      expectedroi:
        formatter: randomFloat
      actualroi:
        formatter: randomFloat
