invoicebillads:
  vtiger_invoicebillads:
    columns:
      bill_city:
        provider: Faker\Provider\en_US\Address
        formatter: city
      bill_code:
        provider: Faker\Provider\en_US\Address
        formatter: postcode
      bill_country:
        provider: Faker\Provider\en_US\Address
        formatter: country
      bill_state:
        provider: Faker\Provider\en_US\Address
        formatter: state
      bill_pobox:
        provider: Faker\Provider\en_US\Address
        formatter: buildingNumber
        optional: true
