potential:
  vtiger_potential:
    columns:
      potentialname:
        formatter: words
      amount:
        formatter: randomFloat
      forecast_amount:
        formatter: randomFloat
      email:
        formatter: email
