asteriskincomingevents:
  vtiger_asteriskincomingevents:
    columns:
      from_number:
        formatter: e164PhoneNumber
      from_name:
        provider: Faker\Provider\en_US\Person
        formatter: lastName
      to_number:
        formatter: e164PhoneNumber
