invoice:
  vtiger_invoice:
    columns:
      subject:
        formatter: sentence
      customerno:
        formatter: randomNumber
      purchaseorder:
        formatter: sentence
      terms_conditions:
        formatter: text
      adjustment:
        formatter: randomFloat
      subtotal:
        formatter: randomFloat
      total:
        formatter: randomFloat
      pl_gross_total:
        formatter: randomFloat
      pl_dto_line:
        formatter: randomFloat
      pl_dto_total:
        formatter: randomFloat
      pl_dto_global:
        formatter: randomFloat
      pl_net_total:
        formatter: randomFloat
      sum_nettotal:
        formatter: randomFloat
      sum_taxtotal:
        formatter: randomFloat
      sum_tax1:
        formatter: randomFloat
      sum_taxtotalretention:
        formatter: randomFloat
      sum_tax2:
        formatter: randomFloat
      pl_sh_total:
        formatter: randomFloat
      sum_tax3:
        formatter: randomFloat
      pl_sh_tax:
        formatter: randomFloat
      pl_grand_total:
        formatter: randomFloat
      pl_adjustment:
        formatter: randomFloat
