project:
  vtiger_project:
    columns:
      projectname:
        formatter: domainWord
      startdate:
        provider: Faker\Provider\DateTime
        formatter: date
      targetenddate:
        provider: Faker\Provider\Internet
        formatter: date
      targetbudget:
        formatter: randomFloat
        optional: true
      projecturl:
        provider: Faker\Provider\Internet
        formatter: url
      email:
        provider: Faker\Provider\Internet
        formatter: email
