contactsubdetails:
  vtiger_contactsubdetails:
    columns:
      homephone:
        provider: Faker\Provider\en_US\PhoneNumber
        formatter: phoneNumber
      otherphone:
        provider: Faker\Provider\en_US\PhoneNumber
        formatter: phoneNumber
      assistant:
        formatter: assistant
      assistantphone:
        provider: Faker\Provider\en_US\PhoneNumber
        formatter: phoneNumber
      birthday:
        formatter: date
      leadsource:
        formatter: leadsource
