assets:
  vtiger_assets:
    columns:
      serialnumber:
        formatter: ean13
      shippingmethod:
        formatter: shuffle
      shippingtrackingnumber:
        formatter: isbn10
      assetname:
        formatter: sentence
      tagnumber:
        formatter: ean8

