assets:
  vtiger_assets:
    columns:
      asset_no:
        provider: Faker\Provider\Miscellaneous
        formatter: md5
      serialnumber:
        formatter: serialnumber
      shippingmethod:
        formatter: shippingmethod
      shippingtrackingnumber:
        formatter: shippingtrackingnumber
      assetname:
        formatter: assetname
