notes:  
  vtiger_notes:
    columns:
      title:
        formatter: title
      filename:
        formatter: filename
      notecontent:
        provider: Faker\Provider\File
        formatter: mimeType
      filetype:
        provider: Faker\Provider\File
        formatter: fileExtension
      filelocationtype:
        formatter: fileloctiontype
      filedownloadcount:
        formatter: filedownloadcount
      filestatus:
        formatter: filestatus
      filesize:
        formatter: filesize
      fileversion:
        formatter: fileversion
      template:
        formatter: template
      template_for:
        formatter: template_for
