campaign:
  vtiger_campaign:
    columns:
      campaignname:
        formatter: words
      expectedrevenue:
        formatter: randomFloat
      budgetcost:
        formatter: randomFloat
      actualcost:
        formatter: randomFloat
      sponsor:
        formatter: name
      targetaudience:
        formatter: words
      expectedsalescount:
        formatter: words
      actualsalescount:
        formatter: words
      expectedresponsecount:
        formatter: words
      actualresponsecount:
        formatter: words
      expectedroi:
        formatter: randomFloat
      actualroi:
        formatter: randomFloat
