inventorydetails:
  vtiger_inventorydetails:
    columns:
      listprice:
        formatter: randomFloat
      extgross:
        formatter: randomFloat
      extnet:
        formatter: randomFloat
      linetotal:
        formatter: randomFloat
      cost_price:
        formatter: randomFloat
      cost_gross:
        formatter: randomFloat
