mailscanner: 
  vtiger_mailscanner:
    columns:
      scannername:
        formatter: scannername
      server:
        provider: Faker\Provider\Internet
        formatter: ipv4
      protocol:
        provider: Faker\Provider\Internet
        formatter: protocol
      username:
        formatter: userName
      password:
        formatter: password
      connectionurl:
        provider: Faker\Provider\Internet
        formatter: url
      searchfor:
        formatter: slug
      markas:
        formatter: markas
