cbtandc:
  vtiger_cbtandc:
    columns:
      cbtandcno:
        formatter: cbtandcno
      reference:
        formatter: reference
      formodule:
        formatter: formodule
      tandc:
        formatter: text
