msgtemplate:
  vtiger_msgtemplate:
    vtiger_msgtemplate:
      columns:
        subject:
          formatter: text
        template:
          formatter: randomHtml(2,3)
        templateonlytext:
          formatter: text